### ISSUE TITLE
Real World Results

### ISSUE THREAD

**Issue by OrkhanHI** [yashasvi97/IJCB2020_anomaly#2]
Hi @yashasvi97,

I tried your released models on several images both with real face, spoof face and no face at all.

In all cases the output from the spoof model is always the same "real" prediction. 

Can you illustrate your work on some real world images.

I have spent the last 3 days trying to understand and test your work.

If this does not work in the real world, I am opening this issue, so that other people do not waste their time.

**Comment by notha99y** [comment]
Hi @OrkhanHI how are you converting the "scores" into predictions? For me, I have tried the released models naively and the "scores" of the real and spoof examples have similar distribution. I had the conclusion that the models could not generalise to my dataset.

**Comment by yashasvi97** [comment]
Hi @OrkhanHI the model is trained only on Replay Attack Dataset. Further since the algorithm is heavily dependent on hyperparameter selection and dataset distribution, it will require training again to make it work for real world images. Further this project is just a proof of concept to guide present and future anti-spoofing systems to be more robust. I am not sure what do you mean by opening an issue? I think what you have done is already opened an issue. 
Hi @notha99y as I mentioned the released model is trained only on replay attack dataset. For your dataset, it might require separate training.

**Comment by yashasvi97** [comment]
closing this for now
